### ISSUE TITLE
urllib2.HTTPError: HTTP Error 999: Request denied and 403: Forbidden

### ISSUE THREAD

**Issue by FelixVicis** [FelixVicis/Google-EmailScraper#1]
From: https://github.com/kennyledet/Google-EmailScraper/issues/3
Tagging @kn9,

------------------------------

Hello @FelixVicis, I get keep getting the error below when I try your forked Google-EmailScraper.
how can I resolve this, please

```
root@Inside:/home/amd/mail# sudo python main.py -query "Manage IT Services" -pages 10 -o ema.csv
Traceback (most recent call last):
File "main.py", line 65, in 
s.go(args.query, args.pages)
File "main.py", line 35, in go
self.scrape(url)
File "main.py", line 43, in scrape
raise e
urllib2.HTTPError: HTTP Error 999: Request denied
root@Inside:/home/amd/mail# sudo python main.py -query "Manage IT Services" -pages 10 -o emaia.csv
Traceback (most recent call last):
File "main.py", line 65, in 
s.go(args.query, args.pages)
File "main.py", line 35, in go
self.scrape(url)
File "main.py", line 43, in scrape
raise e
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by FelixVicis** [comment]
@kn9 fixed the problem. It was a lack in handling http errors via urllib.

If you fetch `master`, your problem should be solved.

**Comment by kn9** [comment]
Ok, Thank you. will give it a try again.
